/**
 * Hindi interface text, keyed by the English text shown on screen.
 * A text that is not listed here stays in English.
 *
 * Figures, Project IDs, report numbers and names of people and places are
 * never translated.
 */
export const HINDI = {
  // ── Navigation ─────────────────────────────────────────────────────────────
  'Dashboard': 'डैशबोर्ड',
  'My Projects': 'मेरी परियोजनाएं',
  'My MPRs': 'मेरी मासिक रिपोर्ट',
  'Deadlines': 'समय-सीमा',
  'Notifications': 'सूचनाएं',
  'District Projects': 'जनपद की परियोजनाएं',
  'Review MPRs': 'मासिक रिपोर्ट समीक्षा',
  'Projects': 'परियोजनाएं',
  'Users': 'उपयोगकर्ता',
  'Audit Logs': 'ऑडिट लॉग',
  'All Reports': 'सभी रिपोर्ट',
  'Advanced Analytics': 'विस्तृत विश्लेषण',
  'MPR Reports': 'मासिक रिपोर्ट',
  'Analytics': 'विश्लेषण',

  // ── Status ─────────────────────────────────────────────────────────────────
  'Draft': 'मसौदा',
  'Submitted': 'प्रस्तुत',
  'Under Review': 'समीक्षाधीन',
  'Approved': 'स्वीकृत',
  'Rejected': 'अस्वीकृत',
  'Resubmitted': 'पुनः प्रस्तुत',
  'Pending Checker Verification': 'चेकर सत्यापन लंबित',
  'Pending Approval': 'अनुमोदन लंबित',
  'Sanctioned': 'स्वीकृत (सैंक्शन)',
  'Forwarded to District': 'जनपद को प्रेषित',
  'Accepted by District': 'जनपद द्वारा स्वीकार',
  'Assigned to PIA': 'पीआईए को आवंटित',
  'Active (PIA Accepted)': 'सक्रिय (पीआईए द्वारा स्वीकार)',
  'Submitted to District': 'जनपद को प्रस्तुत',
  'Approved by District': 'जनपद द्वारा अनुमोदित',
  'Verified by State': 'राज्य द्वारा सत्यापित',
  'Returned for Correction': 'सुधार हेतु वापस',
  'Closed': 'बंद',

  // ── Project detail ─────────────────────────────────────────────────────────
  'Overview': 'सारांश',
  'Budget & Releases': 'बजट एवं अवमुक्ति',
  'Activity Plan': 'गतिविधि योजना',
  'Progress Reports': 'प्रगति रिपोर्ट',
  'Outcomes': 'परिणाम',
  'Completion & Closure': 'पूर्णता एवं समापन',
  'Workflow & Documents': 'कार्यप्रवाह एवं दस्तावेज़',
  'Total Budget': 'कुल बजट',
  'Budget Released': 'अवमुक्त बजट',
  'PIA Departments': 'पीआईए विभाग',
  'Activities Planned': 'नियोजित गतिविधियां',
  'District': 'जनपद',
  'Back to projects': 'परियोजनाओं पर वापस',
  'This project is closed': 'यह परियोजना बंद है',

  // ── Monthly Progress Report: entry ─────────────────────────────────────────
  'Monthly Progress Report': 'मासिक प्रगति रिपोर्ट',
  'Correct Monthly Progress Report': 'मासिक प्रगति रिपोर्ट में सुधार',
  'Report physical and financial progress for your department. Amounts are in ₹ Lakh.': 'अपने विभाग की भौतिक एवं वित्तीय प्रगति दर्ज करें। धनराशि ₹ लाख में है।',
  'Project': 'परियोजना',
  'Only projects assigned to you are listed. Project details are filled automatically.': 'केवल आपको आवंटित परियोजनाएं दिखाई गई हैं। परियोजना का विवरण स्वतः भर जाता है।',
  'The project and period of a returned report cannot be changed.': 'वापस की गई रिपोर्ट की परियोजना एवं अवधि बदली नहीं जा सकती।',
  'Project Name / Unique ID': 'परियोजना का नाम / यूनिक आईडी',
  'Search project…': 'परियोजना खोजें…',
  'Loading projects…': 'परियोजनाएं लोड हो रही हैं…',
  'Search by Project ID, name or village…': 'परियोजना आईडी, नाम या ग्राम से खोजें…',
  'Select a project to begin.': 'शुरू करने के लिए परियोजना चुनें।',
  'Block': 'विकासखंड',
  'Gram Panchayat': 'ग्राम पंचायत',
  'Village': 'ग्राम',
  'Reporting Period': 'रिपोर्ट की अवधि',
  'Choose the financial year and the month you are reporting.': 'वित्तीय वर्ष एवं वह माह चुनें जिसकी रिपोर्ट दे रहे हैं।',
  'Financial Year': 'वित्तीय वर्ष',
  'Progress Entry Month': 'प्रगति का माह',
  'Select financial year': 'वित्तीय वर्ष चुनें',
  'Select month': 'माह चुनें',
  'Select the financial year first': 'पहले वित्तीय वर्ष चुनें',
  'Department': 'विभाग',
  'Select department': 'विभाग चुनें',
  'Head': 'मद',
  'Activity Progress': 'गतिविधि की प्रगति',
  'This is the first report for this department, so previous progress is zero.': 'यह इस विभाग की पहली रिपोर्ट है, इसलिए पूर्व प्रगति शून्य है।',
  'This month cannot be reported': 'इस माह की रिपोर्ट नहीं दी जा सकती',
  'Open report': 'रिपोर्ट खोलें',
  'Remarks': 'टिप्पणी',
  '(optional)': '(वैकल्पिक)',
  "Anything the district should know about this month's progress": 'इस माह की प्रगति के बारे में जनपद के लिए कोई जानकारी',
  'Evidence': 'साक्ष्य',
  'Site photographs or measurement sheets for this month. A report can be submitted without any.': 'इस माह के स्थल के फोटो या माप-पत्र। रिपोर्ट इनके बिना भी प्रस्तुत की जा सकती है।',
  'Summary': 'सारांश',
  'Calculated from the figures above and confirmed by the server before saving.': 'ऊपर के आंकड़ों से गणना की गई; सुरक्षित करने से पहले सर्वर द्वारा पुष्टि की जाती है।',
  'Cancel': 'रद्द करें',
  'Preview': 'पूर्वावलोकन',
  'Validating…': 'जांच हो रही है…',
  'Preview Monthly Progress Report': 'मासिक प्रगति रिपोर्ट का पूर्वावलोकन',
  'Read-only. Nothing is saved until you choose Proceed.': 'केवल देखने हेतु। "आगे बढ़ें" चुनने तक कुछ भी सुरक्षित नहीं होगा।',
  'Back to Edit': 'संपादन पर वापस',
  'Proceed': 'आगे बढ़ें',
  'Submitting MPR…': 'रिपोर्ट प्रस्तुत हो रही है…',
  'MPR Submitted Successfully': 'मासिक रिपोर्ट सफलतापूर्वक प्रस्तुत हुई',
  'Report Resubmitted': 'रिपोर्ट पुनः प्रस्तुत हुई',
  'It has been sent to the district for review.': 'इसे समीक्षा हेतु जनपद को भेज दिया गया है।',
  'File Another Month': 'अन्य माह की रिपोर्ट भरें',
  'View Report': 'रिपोर्ट देखें',

  // Activity table
  'Activity': 'गतिविधि',
  'Physical Progress': 'भौतिक प्रगति',
  'Financial Progress (₹ Lakh)': 'वित्तीय प्रगति (₹ लाख)',
  'Financial Progress': 'वित्तीय प्रगति',
  'Total Target': 'कुल लक्ष्य',
  'Up to Previous Month': 'गत माह तक',
  'During Month': 'माह के दौरान',
  'Total': 'योग',
  'Physical': 'भौतिक',
  'Financial': 'वित्तीय',
  'Target': 'लक्ष्य',
  'Up to previous month': 'गत माह तक',
  'Progress during month': 'माह के दौरान प्रगति',
  'Financial progress during month': 'माह के दौरान वित्तीय प्रगति',
  'Total progress': 'कुल प्रगति',

  // ── My MPRs ────────────────────────────────────────────────────────────────
  'Monthly Progress Reports for the departments assigned to you.': 'आपको आवंटित विभागों की मासिक प्रगति रिपोर्ट।',
  'New Monthly Progress Report': 'नई मासिक प्रगति रिपोर्ट',
  'Reports': 'रिपोर्ट',
  'All': 'सभी',
  'With district': 'जनपद के पास',
  'Returned': 'वापस',
  'Verified': 'सत्यापित',
  'Report': 'रिपोर्ट',
  'Spent This Month': 'इस माह व्यय',
  'Status': 'स्थिति',
  'Open': 'खोलें',
  'You have not filed a monthly progress report yet.': 'आपने अभी तक कोई मासिक प्रगति रिपोर्ट नहीं भरी है।',
  'No report with this status.': 'इस स्थिति की कोई रिपोर्ट नहीं है।',
  'Excel Register': 'एक्सेल रजिस्टर',

  // ── Deadlines ──────────────────────────────────────────────────────────────
  'What is due, what is late and what is waiting.': 'क्या देय है, क्या विलंबित है और क्या लंबित है।',
  'Reminders & E-mail': 'अनुस्मारक एवं ई-मेल',
  'Reports expected': 'अपेक्षित रिपोर्ट',
  'Filed': 'प्रस्तुत',
  'Overdue': 'विलंबित',
  'Due soon': 'शीघ्र देय',
  'Due': 'देय',
  'Skipped': 'छूटी हुई',
  'Due, not yet filed': 'देय, अभी प्रस्तुत नहीं',
  'With district for review': 'समीक्षा हेतु जनपद के पास',
  'Awaiting district review': 'जनपद समीक्षा लंबित',
  'Returned, not corrected': 'वापस, सुधार लंबित',
  'PIA Officer': 'पीआईए अधिकारी',
  'File report': 'रिपोर्ट भरें',
  'File now': 'अभी भरें',
  'Open project': 'परियोजना खोलें',
  'Every expected report has been filed.': 'सभी अपेक्षित रिपोर्ट प्रस्तुत हो चुकी हैं।',
  'No department owes a report for this month.': 'इस माह किसी विभाग की रिपोर्ट देय नहीं है।',
  'No report is waiting for review.': 'कोई रिपोर्ट समीक्षा हेतु लंबित नहीं है।',
  'No returned report is pending.': 'कोई वापस की गई रिपोर्ट लंबित नहीं है।',
  'Monthly reports for {period}': '{period} की मासिक रिपोर्ट',
  'One row for every department that owes this month\'s report.': 'प्रत्येक विभाग की एक पंक्ति जिसकी इस माह की रिपोर्ट देय है।',
  'The report for {period} was due on {date}': '{period} की रिपोर्ट {date} तक देय थी',
  '{count} day overdue': '{count} दिन विलंब',
  '{count} days overdue': '{count} दिन विलंब',
  '{count} day left': '{count} दिन शेष',
  '{count} days left': '{count} दिन शेष',
  'A later month was filed': 'बाद के माह की रिपोर्ट प्रस्तुत हो चुकी है',
  'Not filed': 'प्रस्तुत नहीं',
  "Each month's progress report is due by day {day} of the next month. {next} is due by {date}.": 'प्रत्येक माह की प्रगति रिपोर्ट अगले माह की {day} तारीख तक देय है। {next} की रिपोर्ट {date} तक देय है।',
  'Reminders go out automatically.': 'अनुस्मारक स्वतः भेजे जाते हैं।',
  'Automatic reminders are switched off.': 'स्वचालित अनुस्मारक बंद हैं।',
  'The district has {days} days to approve or return a report.': 'जनपद के पास रिपोर्ट अनुमोदित या वापस करने के लिए {days} दिन हैं।',
  'The PIA officer must correct and resubmit these before filing another month.': 'पीआईए अधिकारी को अगले माह की रिपोर्ट से पहले इन्हें सुधारकर पुनः प्रस्तुत करना होगा।',
  'Nothing in this list.': 'इस सूची में कुछ नहीं है।',
  'Correct': 'सुधारें',
  'Due today': 'आज देय',
};
