export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  DD_LEVEL: 'DD_LEVEL',
  PIA_OFFICER: 'PIA_OFFICER',
  MND_SUPER_ADMIN: 'MND_SUPER_ADMIN',
  MND_OFFICER: 'MND_OFFICER',
};

export const ROLE_LABELS = {
  [USER_ROLES.SUPER_ADMIN]: 'Super Admin',
  [USER_ROLES.DD_LEVEL]: 'District Director',
  [USER_ROLES.PIA_OFFICER]: 'PIA Officer',
  [USER_ROLES.MND_SUPER_ADMIN]: 'MND Admin',
  [USER_ROLES.MND_OFFICER]: 'MND Officer',
};
