export const DPR_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  RESUBMITTED: 'RESUBMITTED',
};

export const STATUS_LABELS = {
  [DPR_STATUS.DRAFT]: 'Draft',
  [DPR_STATUS.SUBMITTED]: 'Submitted',
  [DPR_STATUS.UNDER_REVIEW]: 'Under Review',
  [DPR_STATUS.APPROVED]: 'Approved',
  [DPR_STATUS.REJECTED]: 'Rejected',
  [DPR_STATUS.RESUBMITTED]: 'Resubmitted',
};

export const SANCTION_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_CHECKER: 'PENDING_CHECKER',
  PENDING_APPROVER: 'PENDING_APPROVER',
  SANCTIONED: 'SANCTIONED',
  FORWARDED_TO_DISTRICT: 'FORWARDED_TO_DISTRICT',
  DISTRICT_ACCEPTED: 'DISTRICT_ACCEPTED',
  FORWARDED_TO_PIA: 'FORWARDED_TO_PIA',
  PIA_ACCEPTED: 'PIA_ACCEPTED',
  REJECTED: 'REJECTED'
};

export const SANCTION_STATUS_LABELS = {
  [SANCTION_STATUS.DRAFT]: 'Draft',
  [SANCTION_STATUS.PENDING_CHECKER]: 'Pending Checker Verification',
  [SANCTION_STATUS.PENDING_APPROVER]: 'Pending Approval',
  [SANCTION_STATUS.SANCTIONED]: 'Sanctioned',
  [SANCTION_STATUS.FORWARDED_TO_DISTRICT]: 'Forwarded to District',
  [SANCTION_STATUS.DISTRICT_ACCEPTED]: 'Accepted by District',
  [SANCTION_STATUS.FORWARDED_TO_PIA]: 'Assigned to PIA',
  [SANCTION_STATUS.PIA_ACCEPTED]: 'Active (PIA Accepted)',
  [SANCTION_STATUS.REJECTED]: 'Rejected'
};

export const MPR_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  DISTRICT_APPROVED: 'DISTRICT_APPROVED',
  STATE_VERIFIED: 'STATE_VERIFIED',
  RETURNED_TO_PIA: 'RETURNED_TO_PIA',
  REJECTED: 'REJECTED'
};

export const MPR_STATUS_LABELS = {
  [MPR_STATUS.DRAFT]: 'Draft',
  [MPR_STATUS.SUBMITTED]: 'Submitted to District',
  [MPR_STATUS.DISTRICT_APPROVED]: 'Approved by District',
  [MPR_STATUS.STATE_VERIFIED]: 'Verified by State',
  [MPR_STATUS.RETURNED_TO_PIA]: 'Returned for Correction',
  [MPR_STATUS.REJECTED]: 'Rejected'
};
